// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: chat.proto

package chatserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatServicesClient is the client API for ChatServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServicesClient interface {
	ChatService(ctx context.Context, opts ...grpc.CallOption) (ChatServices_ChatServiceClient, error)
}

type chatServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServicesClient(cc grpc.ClientConnInterface) ChatServicesClient {
	return &chatServicesClient{cc}
}

func (c *chatServicesClient) ChatService(ctx context.Context, opts ...grpc.CallOption) (ChatServices_ChatServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatServices_ServiceDesc.Streams[0], "/chatserver.ChatServices/ChatService", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServicesChatServiceClient{stream}
	return x, nil
}

type ChatServices_ChatServiceClient interface {
	Send(*FromClient) error
	Recv() (*FromServer, error)
	grpc.ClientStream
}

type chatServicesChatServiceClient struct {
	grpc.ClientStream
}

func (x *chatServicesChatServiceClient) Send(m *FromClient) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServicesChatServiceClient) Recv() (*FromServer, error) {
	m := new(FromServer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServicesServer is the server API for ChatServices service.
// All implementations should embed UnimplementedChatServicesServer
// for forward compatibility
type ChatServicesServer interface {
	ChatService(ChatServices_ChatServiceServer) error
}

// UnimplementedChatServicesServer should be embedded to have forward compatible implementations.
type UnimplementedChatServicesServer struct {
}

func (UnimplementedChatServicesServer) ChatService(ChatServices_ChatServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatService not implemented")
}

// UnsafeChatServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServicesServer will
// result in compilation errors.
type UnsafeChatServicesServer interface {
	mustEmbedUnimplementedChatServicesServer()
}

func RegisterChatServicesServer(s grpc.ServiceRegistrar, srv ChatServicesServer) {
	s.RegisterService(&ChatServices_ServiceDesc, srv)
}

func _ChatServices_ChatService_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServicesServer).ChatService(&chatServicesChatServiceServer{stream})
}

type ChatServices_ChatServiceServer interface {
	Send(*FromServer) error
	Recv() (*FromClient, error)
	grpc.ServerStream
}

type chatServicesChatServiceServer struct {
	grpc.ServerStream
}

func (x *chatServicesChatServiceServer) Send(m *FromServer) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServicesChatServiceServer) Recv() (*FromClient, error) {
	m := new(FromClient)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServices_ServiceDesc is the grpc.ServiceDesc for ChatServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatserver.ChatServices",
	HandlerType: (*ChatServicesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatService",
			Handler:       _ChatServices_ChatService_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}
